Voynova lesson 7
OlgaVoynova/home-work pull request #5
Opened 2021-11-29 19:35 UTC by OlgaVoynova

Add comparison functionality

2021-11-29 19:42 UTC, OlgaVoynova commented on src/main/java/com/sbrf/reboot/account/entity/Account.java
> +@AllArgsConstructor
Норм использовать обе аннотации (all и required args constructor)?

2021-11-29 19:44 UTC, OlgaVoynova commented on src/test/java/com/sbrf/reboot/service/AccountServiceTestMock.java
> +        account = new Account(ACCOUNT_ID,CLIENT_ID);
Тест изменен ради сокращения количества конструкторов + выглядит так, что поле clientId должно быть обязательным

2021-12-05 16:24 UTC, Upforup commented on src/main/java/com/sbrf/reboot/account/entity/Account.java
> +@AllArgsConstructor
Да, но обычно рекомендуется использовать статические factory методы.

2021-12-05 16:47 UTC, Upforup requested changes
Есть замечания.

2021-12-05 16:47 UTC, Upforup commented on src/main/java/com/sbrf/reboot/account/entity/Account.java
> +        if (this.id.equals(object.getId()) || this == object ) {
1 Comparable#compareTo должен выбрасывать NPE в случае переданного аргумента null
2 На мой взгляд первое условие лишнее, если натуральный порядок основан на значении ID то достаточно вернуть id.compareTo(object.getId())ю
3. Equals в compareTo вызывать не требуется.

2021-12-05 16:47 UTC, Upforup commented on src/main/java/com/sbrf/reboot/utils/comparator/AccountComparatorIdDate.java
> +public class AccountComparatorIdDate implements Comparator<Account> {
Предлагаю рассмотреть возможности композиции Comparator, в метод сортировки можно передать примерно следующую реализацию Comparator.comparing(Account::getId)
                .thenComparing(Account::getCreateDate). Так код будет гораздо компактнее и не потребуется писать собственную реализацию.

2021-12-26 13:45 UTC, OlgaVoynova commented on src/main/java/com/sbrf/reboot/account/entity/Account.java
> +        if (this.id.equals(object.getId()) || this == object ) {
done

2021-12-26 13:45 UTC, OlgaVoynova commented on src/main/java/com/sbrf/reboot/utils/comparator/AccountComparatorIdDate.java
> +public class AccountComparatorIdDate implements Comparator<Account> {
done

2021-12-26 14:06 UTC, OlgaVoynova commented on src/main/java/com/sbrf/reboot/account/entity/Account.java
> +        if (this.id.equals(object.getId()) || this == object ) {
+ посмотри, плиз, на реализацию того, как я поняла static factory method вместо конструкторов в классе Account (почему-то не могу туда коммент поставить - видимо, после коммита). Как я понимаю, еще можно было бы делать их с одинаковыми именами и переопределять с разными сигнатурами, но остановилась на человекочитаемых названиях

2021-12-30 16:49 UTC, Upforup approved these changes
OK

2022-01-01 16:14 UTC, merged